# SPDX-FileCopyrightText: 2024-2025 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: MIT

fail-on-severity: critical

scan:
  # force SBOM correlation
  sbom:
    enabled: true

ignore:
  - vulnerability: CVE-XXXX-YYYY
    reason: "False positive for debian:bookworm-slim"
