# SPDX-FileCopyrightText: 2024-2025 Rafael V. Volkmer <rafael.v.volkmer@gmail.com>
# SPDX-License-Identifier: MIT

vulnerability:
  ignore-unfixed: true
  severities:
    - CRITICAL
    - HIGH

misconfiguration:
  include-non-failures: false

license:
  policy: "warn"